name: Deploy to Server
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    environment: Test
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v4
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: |
            ${{ steps.yarn-cache-dir-path.outputs.dir }}

          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - uses: actions/cache@v4
        id: next-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: |
            # ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-
            ${{ runner.os }}-nextjs-
      - name: Install dependencies
        run: yarn
      - name: Build
        run: |
          yarn build
      - name: Package Build
        run: |
          mkdir -p campwiz-frontend
          mv .next campwiz-frontend
          mkdir .next 
          cp -r campwiz-frontend/.next/cache .next
          cp package.json campwiz-frontend
          cp yarn.lock campwiz-frontend
          cp -r public campwiz-frontend
          cp next.config.* campwiz-frontend
      - name: Setup Deployment Environment
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > id_rsa
          chmod 600 id_rsa
      - name: Send Build to Server
        run: |
          rsync -Pav --no-perms --omit-dir-times -e "ssh -i id_rsa" campwiz-frontend/ "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.SSH_REMOTE_PATH }}"
      - name: Restart Campwiz
        run: |
          ssh -i id_rsa "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}" "cd ${{ secrets.SSH_REMOTE_PATH }} && yarn && pm2 restart campwiz-frontend --update-env"
      - name: Delete SSH Key
        run: |
          rm id_rsa
